FROM python:3.12-slim

WORKDIR /ebcra-2-web

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY / .

EXPOSE 8000

CMD ["gunicorn", "ebcra.wsgi:application", "--bind", "0.0.0.0:8000", "--workers", "2"]

#CMD ["sleep", "infinity"]
